### PR TITLE
Fix leak of .flatpak-info fd

### LINKED ISSUE #352: Crash due to fd leak
See https://bugzilla.redhat.com/show_bug.cgi?id=1730327. xdg-desktop-portal has opened the ./flatpak-info file >1000 times and is unable to allocate more fds.

I think the problem is in parse_app_info_from_flatpak_info(), in xdp-utils.c.

### PR DESCRIPTION
**Pull request by mcatanzaro**
Fixes #352

Because xdg-desktop-portal is kinda hard to set up and run, this is a low-effort **untested** merge request. No warranty. But it looks right. We might need to keep info_fd open until we're done with the GMappedFile that's using it -- not sure -- but at this point we are already done with it, so should be OK.

### CODE REVIEW

File: src/xdp-utils.c [hunk 1]
```diff
@@ -440,8 +440,12 @@ parse_app_info_from_flatpak_info (int pid, GError **error)
     group = "Runtime";
 
   id = g_key_file_get_string (metadata, group, "name", error);
-  if (id == NULL)
+  if (id == NULL) {
```
Comment (matthiasclasen) [inline src/xdp-utils.c]: { on the next line here, please.

**Comment by matthiasclasen** [comment]
Looks correct, other than that.

File: src/xdp-utils.c (hunk 1 above)
Comment (mcatanzaro) [reply src/xdp-utils.c]: Oops, sorry. Long day yesterday....
